### PR TITLE
WIP: Static IP Mapping

### PR DESCRIPTION
**Pull request by dynacylabs**
This is a WIP PR for adding Static IP Mapping to the esp32_nat_router_extended. It is not fully implemented, as I think it will require writing a custom DHCP server in order to assign IP's to clients in a predictable manner. 

Hopefully this is a start to getting this feature implemented. As mentioned above, it doesn't look like esp-idf allows us to assign IP addresses currently, but the ability to assign an IP address should exist within the dhcp server portion of the lwip component. My hope is to continue pursuing this avenue unless someone has a different approach they think could work. 

Some interesting links that may be of use:
- https://github.com/espressif/esp-idf/blob/master/components/lwip/apps/dhcpserver/dhcpserver.c
- https://github.com/espressif/esp-idf/blob/master/examples/protocols/static_ip/main/static_ip_example_main.c

I also would appreciate any and all feedback as I am not an HTML/callback expert. Also my C is a little rusty so I could have messed that up as well. 

What's currently implemented:
- UI for adding/deleting static IP mappings (modeled after the portmap feature)
- Back end for storing static IP mappings in nvs (modeled after the portmap feature)
- CLI interface for adding/deleting static IP mappings (modeled after portmap and `set_sta` interfaces)
- UI for displaying saved static IP mappings (modeled after the connected clients table in `clients.html` and the portmap feature) (currently pseudo code)
Currently untested. Feel free to close this PR if it will not be of benefit. 

Thanks for an awesome project!

### CODE REVIEW

**Comment by dchristl** [comment]
Hello @dynacylabs 

thanks for your work. I will have a deeper look, when I have time. 
The UI and saving are generally not the problem, but integrating the DHCP server is. I have already tried some things, and all the examples I found were outdated or simply did not work. I have come across various DHCP server implementations (including yours from the link), but nowhere is there information on how to integrate/activate it. At first glance, it seems to be missing in your pull request as well, or did I overlook it? If I could find a working example for integration, the rest would not be a problem.
I'm at the point where it seems simply not possible to assign static IPs, but I might take a closer look at it when I have the opportunity and more time.

Kind regards,
Danny

**Comment by dchristl** [comment]
@dynacylabs 

I've seen you pushed some more commits after my comment. Please read my comment first! Otherwise, I'm afraid all your work might be in vain. So far, you've only focused on the UI and saving the settings. That is never the issue with the functionality of the mapping but rather the integration/activation of the DHCP server in **softAP** mode. I have struggled with it, so you should focus on that first. Just try to "simply" assign an arbitrary client, for example, the IP 192.168.4.77 via DHCP. If that somehow works, then the settings are the least of our problems. As I mentioned, after my attempts and research, I've come to the conclusion that this simply doesn't work in softAP mode. Maybe you'll have more success.

**Comment by dynacylabs** [comment]
Hi @dchristl 

I understand that the UI was never the issue. My hopes with putting this PR up was that the opposite was true: you had determined a method to assign static IP's and that perhaps the UI was the sticking point. To help with deduplicating any effort in my research, could you describe the methods you have tried or investigated for setting static IP's?

I am looking at an implementation similar to this to start:

```
void assign_static_ip() {
    // MAC address of the client
    uint8_t mac[6] = {0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF};

    // Static IP to assign
    ip4_addr_t client_ip;
    IP4_ADDR(&client_ip, 192, 168, 4, 2);

    // Create and set IP information
    dhcp_ip_addr_t ip_info;
    memset(&ip_info, 0, sizeof(ip_info));
    memcpy(ip_info.mac, mac, sizeof(mac));
    ip_info.ip = client_ip;

    // Add static IP to DHCP lease
    ESP_ERROR_CHECK(tcpip_adapter_dhcps_option(
        TCPIP_ADAPTER_OP_SET,
        TCPIP_ADAPTER_REQUESTED_IP_ADDRESS,
        &ip_info, sizeof(ip_info)
    ));
}```

Where, for each static ip assignment, this method would get called with the necessary parameters.

**Comment by dynacylabs** [comment]
Withdrawing until I have gotten more work on this done.

**Pull request closed without merging**
